// Generated by scripts/generate-official-lock.mjs; do not edit.
// rust-style-allow: large-file - generated official-skill lock table is kept
// contiguous so digest/version updates remain mechanical and reviewable.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct OfficialSkillLockEntry {
    pub(crate) skill_id: &'static str,
    pub(crate) version: &'static str,
    pub(crate) digest: &'static str,
}

pub(crate) const OFFICIAL_SKILLS: &[OfficialSkillLockEntry] = &[
    OfficialSkillLockEntry {
        skill_id: "runx/agency",
        version: "sha-7278903df3df",
        digest: "01339546cbb21bcb1d16b371a8942c46e0ee6789f68e470eac7b0e5993d866c7",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/brand-voice",
        version: "sha-79c56911c0ba",
        digest: "54bf1ed1013ebc91a5491fb86f15a1bda2e872ac073a12680c58278af0867528",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/business-ops",
        version: "sha-75acf9d53694",
        digest: "7801492f5b8fa34f0f6e91f9f2729396744c35fe517ae275885e07204bc52b6f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/charge",
        version: "sha-0d05afcfa6ae",
        digest: "c151b98be3a2a7ccd306d7395d906ffd1fc22e45a7d94ffe34c294e9db1c47ce",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/content-pipeline",
        version: "sha-0a1e30996cf8",
        digest: "c6c210735ca826875959c5eb3c2420c50aee52eb3723b19be7369e9da85552a5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/data-store",
        version: "sha-4ce123197d50",
        digest: "fbf0c7356f063f4fa12c9ff3bd944587f9202fb1520238a6652c90c907cb062f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/deep-research-brief",
        version: "sha-9fbd590b60ee",
        digest: "0b771c3ebeb63b0178b299f1dbbcec37cbd97e6db6d00037b18f3cb050ed03c0",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/dependency-cve-audit",
        version: "sha-6db720882ba0",
        digest: "427c964bccd3f5f41c71a90905dd74225547e8b7af11015978e4550db3c27249",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/design-skill",
        version: "sha-ef911adf3472",
        digest: "3fb6281273b115959383ed661e41bbbb0588437fb0fc3495c15e17ed3e93a0fa",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/dispute-respond",
        version: "sha-39c3ae5164c4",
        digest: "81469e87f29886e11b27faa2249a4e83fae59659f84f6628c81da7de0bf762c5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/draft-content",
        version: "sha-f67cd3ad3a30",
        digest: "8eefbda1c91d397a4aee14e902f3526cc9b5700c84b08fc528994d26061d12d3",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ecosystem-brief",
        version: "sha-b7396a6e4fb7",
        digest: "a9a277fef0a37fee799d25c70ff81615f5d76bd7d8a217ce2653603f3e3f4138",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ecosystem-vuln-scan",
        version: "sha-38e41a60447e",
        digest: "0db0736afc0ccbf0b5e05000f37a3136c4ebd8520208439779915d8c40ff9811",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/evolve",
        version: "sha-e0e2b933e8a7",
        digest: "aa446e7d3ab8a3168facd2372b8bd8fe63736a3e061438d38cc83ea8f294b971",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/exact-cve-audit",
        version: "sha-bce4476cee8b",
        digest: "bf49029b9e20629aed3f8e29dae50fc8e2b2f402e2edb9c1fba2fc6767cb583a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/github-sync",
        version: "sha-e685e9e8b5c6",
        digest: "6981adc877736f05a41d764b3e42d479d87de3bc2d69a65992dff457b635bd9a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/governed-outbound",
        version: "sha-c5be779c857d",
        digest: "20798f5c0b638bfcbb1259179c4810f64f3cdb76f742ac1afa94f8c04617b15b",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/improve-skill",
        version: "sha-73e69bae0a5f",
        digest: "f083e32ee65bcb6f6f338e8f98443fdb2546b8f63bdc6fcea234897eb30e762b",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/inbox-and-calendar-exec",
        version: "sha-7562c7725d96",
        digest: "ed005226e958fc377cc025eb3e329d2a108dd06c0c43e49c6d8f05c41e341319",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-intake",
        version: "sha-e1935534f17a",
        digest: "4b6a78d038e0d0a630e8614a95b212324af8e65a617cbb507ac362151f6faab5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-to-pr",
        version: "sha-6d8933ac61e5",
        digest: "b58c10476991cd2828f7d8b9357ac9b1962eecc3a8d13dd0d036298e1739dd50",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-triage",
        version: "sha-8805b52282dc",
        digest: "97aceb246dbc14544017bde2ff448431cd601d1345852314837c1d86807e587b",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/knowledge-router",
        version: "sha-95a9a4b4671f",
        digest: "584c2a0269331cad16c3ea4b63bf51e38c34aae0dc434629b8f407ca5c9a75d4",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/lead-enrichment",
        version: "sha-4030809766b5",
        digest: "802598ffc48634ee68df5833227407c58ccf3182a6de10d4001e5f764b532329",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/lead-router",
        version: "sha-bb1bb27c20ba",
        digest: "4a27b60d2cdd54a5f02163473f756185f9fa5cb57e32c1f59f65fe3472ed3202",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/least-privilege-auditor",
        version: "sha-a31f1c09aa5c",
        digest: "244df5dd8eed7900d1987c76060893d3c9cd65f420c5b8c177b19fa4e0b81ac2",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ledger",
        version: "sha-00694f04b6d3",
        digest: "f91e656d6fcef27dec6e12725c8015be47762514278f37342ff40761838e9f6c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/messageboard",
        version: "sha-7b9930ac9727",
        digest: "7fb6092161a234fbea28681ec5e72afd9c2d380e547cf4ef97683f28bb9a6427",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-charge",
        version: "sha-33a811c1c7de",
        digest: "54dd044edbcbe8808c6e80177628b5cb039c0f7ed91d9f6d526e55ebb2130841",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-pay",
        version: "sha-0f79c9033107",
        digest: "abd8f7f72eac658e8dba4d642bd66f59646969aebe58cbdc15692cc82b69021d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-refund",
        version: "sha-f5c5c9b340ba",
        digest: "e54cb774724bbf535ce02b7b1b686eca21fe45e8b2589a86aae935b558384ed5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/moltbook",
        version: "sha-35ce15198735",
        digest: "5af0f25863a60fea243dd1cf31cfe1fa7c24a93e4307727a70771a7a26f3f4dc",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-charge",
        version: "sha-56a6df2641cf",
        digest: "833374862eee319c9c007cbecd122342980972fca44556c63381e85ab95ec500",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-pay",
        version: "sha-451f49202ff4",
        digest: "1ff58b3687c33a26e19a52ef8bb5b23b33c99628a81f6041b3c1b8ec27315603",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-refund",
        version: "sha-a96d3310b0c8",
        digest: "9f4b6bcc9bf7cf6578a7906192ab9a6ff20e938836a5e0dc15ff3233af4f18e6",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/n8n-handoff",
        version: "sha-494a1c3f5246",
        digest: "f6016f4f2d5794e82d57c7d5dfec73d8e3485be525fa58760e216da8e46407e0",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/nitrosend",
        version: "sha-430880d628cb",
        digest: "e7761800cb158178fd1e8f41f594404c1a5b2a0c313ee229ed862fa64ca126b7",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/nws-weather-forecast",
        version: "sha-0aeb4bcf16d3",
        digest: "382cdef84f660e7cfdc2dbbfd7e8382d204d1f4ee46ffa019549615f9c2f745c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/open-meteo-weather-forecast",
        version: "sha-5d9f95438c9a",
        digest: "041e0ec18fa4b646b46b72d34662eabbbfbc43ab5a3a65423b49b3e94e81d159",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/operator-inbox",
        version: "sha-b8388bfc3910",
        digest: "368dd1ece62cbab35a597893210ee296af86cc42e1e7c61a0c174177428df05d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ops-desk",
        version: "sha-d52b6967bf71",
        digest: "dda3251b728684ac822e9167aa7eb191327c6939546b533acb95ebf9021c99c5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/overlay-generator",
        version: "sha-b5dc11a7088d",
        digest: "e19bbe8dc5f3bf732dc265a1808819587e67759fdf3014d89bc9bf6629400b18",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/policy-author",
        version: "sha-a1f056d7c7f7",
        digest: "b3bbcbda2711d78c59c572d99206c3116347e9751506301ca40a52c75e85bc84",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/pr-review-note",
        version: "sha-537dd9fc3c6b",
        digest: "b073ec884f56c9e412d0c1039d5f28f163df0f5530eb0bee922ed4c557955c52",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/prior-art",
        version: "sha-f9fad0d3ad4e",
        digest: "02714bb1e0477a609b6af2d5204279bb7155d141975f51f9bb19971615e1f9cf",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/receipt-auditor",
        version: "sha-acbe46a62851",
        digest: "155c522fb8e029bc4bd83863ea0960e23a8936c47977b70052aa9b119675d61e",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/redact-pii",
        version: "sha-1f97fa953efd",
        digest: "200d22c5e671b89e0ac8b837564c3a27e17ba6eb5bf93c80277966e981cf2b52",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/reflect-digest",
        version: "sha-5dccbad9b801",
        digest: "0d94edb32b6750d9de93c6826fb03c0b26f208c2a226608c1b197062034071f3",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/refund",
        version: "sha-fcff39905510",
        digest: "1295dd1950b137f828319d3d56491241ba8629c56ede9e50a736e61e96dd1a9a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/release",
        version: "sha-9d907a90f72b",
        digest: "ad27b35e73a9cef0834edc4bcff47ec86d0967dc690147198fcd2a5fdbb65da5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/research",
        version: "sha-fe6b0b63aaa2",
        digest: "f524007b2e95225075275ac9ce3551e797896581cf734380821208874f74d45f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/review-receipt",
        version: "sha-d64d17c7951c",
        digest: "35ceaff088fe164b1ff716a15e29a2d8cac250026a0067434d238bd2452c379b",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/review-skill",
        version: "sha-810880b3ab12",
        digest: "6ef28bc12e03738383418d61ae5baffc2cb22dd4b18fb441c080cb7b03d57a7c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/run-history-analyst",
        version: "sha-93f2c06be7a8",
        digest: "4dc3ebe026123aa37e2e802086126dd86e70290b8680e507f66174fd1c840b6f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sandbox-harden",
        version: "sha-e5f346fbac0f",
        digest: "15676f191d6878edf96006b006ad78dda6c53f5128f7e3e84fa346941a635fdc",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/send-as",
        version: "sha-651aa8334761",
        digest: "cb8959b40115d1090a1f6da7902b3ce5cd6c735adf09fb4e89f25d31ef16e88f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/settle-invoice",
        version: "sha-d691c9e3ccef",
        digest: "4fc9e01c12e2de29066f737ab18f0e5e532c40543f5af3ce356b95548c4d1687",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sign-receipt",
        version: "sha-03e0b8268637",
        digest: "fc5e848c9a8a1e7ae22de8839789ad949038e2cf699081c1cbeab116bfd73e6a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/skill-lab",
        version: "sha-626d3797b33d",
        digest: "f5da56c0b1ca9f23c5acc1de11685bb98910ee82377ad2685781f0a94b5f2c4d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/skill-testing",
        version: "sha-709a53482c3e",
        digest: "233d2c8af322173a1290855be03e9db977234b8c474353a24ee484d3f7867f0a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/slack-notify",
        version: "sha-84710c6d78fe",
        digest: "9e0abd47c54455add3c715e18c371c427e0bbb0d617ed0212f60d766f62c2856",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sourcey",
        version: "sha-26673ed919b2",
        digest: "30b7e7396d54f0b617dfb67d4c5c6506aaf9dd8df27cac546a9f0f51ff367670",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/spend",
        version: "sha-60c4c4e0874c",
        digest: "d5a5df47cd59faa2cc046a79fe44db6343c068483dae9bf8a470e3506bf90671",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sql-analyst",
        version: "sha-9b5e1b31693d",
        digest: "9508acb26e82956610cad656a80e76474f27dda5573bb58605e9f463fbfdde63",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-charge",
        version: "sha-9ae10a52e3de",
        digest: "1af8a9a9fbc04fbda41b50c0e8a41b61eaeb0e12d9dcfd16f79e268ad00fb3e6",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-pay",
        version: "sha-abedce5a00c1",
        digest: "a5a05ee2c45d0f4a5c2f526cfdcb8af099c673ace97f10d8e392a7f3a0bf5f2b",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-refund",
        version: "sha-4f8b79e11c91",
        digest: "892765b749dcb3698d86c40a297520794c03d10f8aa38fc734393414652648f1",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/structured-extraction",
        version: "sha-22eeb86d17f4",
        digest: "2c83db0c1f170af2e84ca0237e0850108254415bdcffdc57d2a6e66197cef133",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/support-triage-reply",
        version: "sha-93233458fd14",
        digest: "5c6fc18bf3013a1845de83641147f8421ceb1599269e4b3ed111d25e75053fda",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/taste-profile",
        version: "sha-30ae4695f7a2",
        digest: "bebc7d42b982295105d1da03ea392f1384977269adf1705905e1833e73dc78ae",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/twitter",
        version: "sha-fa626edc2e29",
        digest: "dfefb373da5c482f3b3ccda73cf6d963764b1303dde40a75a0c37e25e79865fd",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/vault-unseal",
        version: "sha-15cd18f5b44e",
        digest: "0c2210ff956c0fca388ff3829f31946aa21e02626ee3ae29aee41ff94dd3cc10",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/vuln-scan",
        version: "sha-579dd88a50e3",
        digest: "204fc20915f6d2e35c9c934340929904a3b11f5632db24c39d4afaa6448036c5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/weather-forecast",
        version: "sha-498fe9afa450",
        digest: "2d104a7c806819c53c62f475e5d44e21ebefd940302a0b15b268721a5ee7f426",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/web-fetch",
        version: "sha-9c07d1ee7a62",
        digest: "9d744ec5179a797007727f63eab50ac5d45b321d07a7de73a31baa2b60e1c5a8",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/work-plan",
        version: "sha-68d057ce7577",
        digest: "56d13c36d41cfe8a0915aaf846f112499de4d7a339c96c0601776c50c7999fe5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/write-harness",
        version: "sha-94e5f7441d1a",
        digest: "2c723ea7e868838f71e575eafd30775b3663ecb1ac57fc8f0c592592c21e7892",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/x402-pay",
        version: "sha-008aef3f3b2e",
        digest: "18e4e8c85606f201463d29f4aca8cf910f84293a720a68b2090bd0df1544a62c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/zapier-handoff",
        version: "sha-c4d57d9d21f6",
        digest: "9770ca166baffd03baa4551a6787e1fd1bc5857fb420f351846381efffbbf47d",
    },
];

pub(crate) fn official_skill_entry_by_name(name: &str) -> Option<&'static OfficialSkillLockEntry> {
    let normalized = name.trim();
    OFFICIAL_SKILLS.iter().find(|entry| {
        entry.skill_id == normalized
            || entry
                .skill_id
                .strip_prefix("runx/")
                .is_some_and(|skill_name| skill_name == normalized)
    })
}
